### ISSUE TITLE
Simple Todos 4 - event.target.x.value

### ISSUE THREAD

**Issue by mjmasn** [meteor/simple-todos#29]
This line from section 4.2 doesn't work in safari if referring to a radio button input:

``` javascript
var text = event.target.text.value;
```

It's not a bug with the tutorial itself but confused me for a few minutes when I tried using the same technique to get the value of a radio button. It worked in Chrome but not Safari. May be worth pointing out an alternative technique that works for all input types, although I'm not even sure what the most 'correct' solution is for this these days...

**Comment by stubailo** [comment]
Yeah I think this boils down to learning JavaScript and the browser APIs, I don't think it's a Meteor specific issue. Especially because, as you said, there isn't a catch-all solution. Maybe jQuery provides something?

**Comment by vyasbhavin** [comment]
Indeed, the Safari API seems to be a bit different. Safari creates an array of all radio buttons values and you check if any one of them is 'checked'
For reference, here is what I did for radio buttons which works on both Safari and Chrome (I haven't tested other browsers)

Instead of:
`var radio = event.target.radio.value`

do:

```
if (event.target.form.response[0].checked){
     var response = 'y';
 };
if (event.target.form.response[1].checked){
      var  response = 'n';
 };
```
