### ISSUE TITLE
Username not displayed with current code

### ISSUE THREAD

**Issue by nagarify** [meteor/simple-todos#33]
### 9.6  Display username next to task simple-todos.html »
       
       <input type="checkbox" checked="{{checked}}" class="toggle-checked" />
       <span class="text"><strong>{{username}}</strong> - {{text}}</span>
   
        change to,

        <input type="checkbox" checked="{{checked}}" class="toggle-checked" />
       <span class="text"><strong>{{currentUser.username}}</strong> - {{text}}</span>

##### {{username}} to {{currentUser.username)) 

Thanks

**Comment by stubailo** [comment]
@nagarify the code you have written displays the username of the user that is currently logged in, rather than the username of the user who created the todo item.

If nothing is being displayed with the code snippet from the tutorial, then you either have stale items that don't have a username field, or an error in the place where the todo item is inserted.
